version: '3'
services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # this essentially means do not do a mapping against /app/node_modules inside the container.
      - /app/node_modules
      - .:/app

  #creating a 2nd service for test
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    #over ride default command 
    command: ["npm", "run", "test"]


  
